# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import user_pb2 as user__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServicesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UserDetail = channel.unary_unary(
                '/src.server.proto.user.UserServices/UserDetail',
                request_serializer=user__pb2.UserRequest.SerializeToString,
                response_deserializer=user__pb2.UserBase.FromString,
                _registered_method=True)
        self.UserList = channel.unary_unary(
                '/src.server.proto.user.UserServices/UserList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=user__pb2.UserListResponse.FromString,
                _registered_method=True)
        self.UserSignIn = channel.unary_unary(
                '/src.server.proto.user.UserServices/UserSignIn',
                request_serializer=user__pb2.UserSignInRequest.SerializeToString,
                response_deserializer=user__pb2.UserBase.FromString,
                _registered_method=True)
        self.UserSignUp = channel.unary_unary(
                '/src.server.proto.user.UserServices/UserSignUp',
                request_serializer=user__pb2.UserSignUpRequest.SerializeToString,
                response_deserializer=user__pb2.UserBase.FromString,
                _registered_method=True)
        self.UserSearch = channel.unary_unary(
                '/src.server.proto.user.UserServices/UserSearch',
                request_serializer=user__pb2.UserSearchRequest.SerializeToString,
                response_deserializer=user__pb2.UserListResponse.FromString,
                _registered_method=True)
        self.UserUpdate = channel.unary_unary(
                '/src.server.proto.user.UserServices/UserUpdate',
                request_serializer=user__pb2.UserUpdateRequest.SerializeToString,
                response_deserializer=user__pb2.UserBase.FromString,
                _registered_method=True)
        self.UserDelete = channel.unary_unary(
                '/src.server.proto.user.UserServices/UserDelete',
                request_serializer=user__pb2.UserRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class UserServicesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UserDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserSignIn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserSignUp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UserDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.UserDetail,
                    request_deserializer=user__pb2.UserRequest.FromString,
                    response_serializer=user__pb2.UserBase.SerializeToString,
            ),
            'UserList': grpc.unary_unary_rpc_method_handler(
                    servicer.UserList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=user__pb2.UserListResponse.SerializeToString,
            ),
            'UserSignIn': grpc.unary_unary_rpc_method_handler(
                    servicer.UserSignIn,
                    request_deserializer=user__pb2.UserSignInRequest.FromString,
                    response_serializer=user__pb2.UserBase.SerializeToString,
            ),
            'UserSignUp': grpc.unary_unary_rpc_method_handler(
                    servicer.UserSignUp,
                    request_deserializer=user__pb2.UserSignUpRequest.FromString,
                    response_serializer=user__pb2.UserBase.SerializeToString,
            ),
            'UserSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.UserSearch,
                    request_deserializer=user__pb2.UserSearchRequest.FromString,
                    response_serializer=user__pb2.UserListResponse.SerializeToString,
            ),
            'UserUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.UserUpdate,
                    request_deserializer=user__pb2.UserUpdateRequest.FromString,
                    response_serializer=user__pb2.UserBase.SerializeToString,
            ),
            'UserDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.UserDelete,
                    request_deserializer=user__pb2.UserRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'src.server.proto.user.UserServices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('src.server.proto.user.UserServices', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserServices(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UserDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.server.proto.user.UserServices/UserDetail',
            user__pb2.UserRequest.SerializeToString,
            user__pb2.UserBase.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.server.proto.user.UserServices/UserList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            user__pb2.UserListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserSignIn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.server.proto.user.UserServices/UserSignIn',
            user__pb2.UserSignInRequest.SerializeToString,
            user__pb2.UserBase.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserSignUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.server.proto.user.UserServices/UserSignUp',
            user__pb2.UserSignUpRequest.SerializeToString,
            user__pb2.UserBase.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.server.proto.user.UserServices/UserSearch',
            user__pb2.UserSearchRequest.SerializeToString,
            user__pb2.UserListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.server.proto.user.UserServices/UserUpdate',
            user__pb2.UserUpdateRequest.SerializeToString,
            user__pb2.UserBase.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.server.proto.user.UserServices/UserDelete',
            user__pb2.UserRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
